name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Ensures repo files are available

      - name: Debug - List files
        run: ls -R summary/figures  # Confirms the image exists

      - name: Convert Markdown to PDF using Pandoc with LaTeX
        uses: docker://pandoc/latex:3.5
        with:
          args: "--resource-path=summary summary/summaryAGRSI.md -o output/test.pdf"

      - name: Ensure Output Exists
        run: ls -lh output/  # Check if test.pdf exists

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Converted-PDF
          path: output/test.pdf
