name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Ensures repo files are available

      - name: Debug - List repository files
        run: ls -R  # Confirms file structure

      - name: Convert Markdown to PDF using Pandoc with LaTeX
        uses: docker://pandoc/latex:3.5
        with:
          args: "summary/summaryAGRSI.md -o test.pdf"
